# Generated by Django 4.2.11 on 2024-06-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("category_image", models.ImageField(upload_to="upload/category")),
            ],
        ),
    ]
